import { readFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const files = ["index.html", "styles.css", "app.js", "supabase-client.js", "sw.js", "manifest.webmanifest", "assets/icon.svg", "vercel.json", "scripts/build.mjs", "config.js", "supabase/migrations/202607180001_initial_schema.sql", "supabase/migrations/202607180002_member_approval_and_activity.sql", "supabase/migrations/202607180003_member_fund_schedules.sql", "supabase/migrations/202607180004_pseudo_member_login.sql", "supabase/migrations/202607180005_payment_allocation_and_member_deletion.sql", "supabase/migrations/202607180006_payment_reversals_and_push.sql", "supabase/migrations/202607190007_dynamic_funds_and_due_refresh.sql", "supabase/migrations/202607190008_governance_import_and_meeting.sql", "supabase/migrations/202607190009_future_prepayment_periods.sql", "supabase/migrations/202607190010_paid_through_baseline.sql", "supabase/migrations/202607190011_paid_through_cash_movement.sql", "supabase/functions/send-payment-push/index.ts", "supabase/functions/send-due-reminders/index.ts", "supabase/cron/setup_due_reminders.sql.template"];
const contents = Object.fromEntries(await Promise.all(files.map(async (file) => [file, await readFile(join(root, file), "utf8")])));

const checks = [
  ["manifest standalone", contents["manifest.webmanifest"].includes('"display": "standalone"')],
  ["orientation mobile", contents["manifest.webmanifest"].includes('"orientation": "portrait-primary"')],
  ["viewport et safe-area", contents["index.html"].includes("viewport-fit=cover") && contents["styles.css"].includes("env(safe-area-inset-bottom)")],
  ["mode plein écran", contents["styles.css"].includes("100dvh")],
  ["service worker v19", contents["app.js"].includes("serviceWorker.register") && contents["sw.js"].includes("jappo-cotiz-v19")],
  ["cache de lecture sans démo", contents["app.js"].includes("jappo-cotiz-read-cache-v3") && contents["app.js"].includes("payments: []") && contents["app.js"].includes("activities: []")],
  ["deux caisses initiales sans données fictives", contents["app.js"].includes('{ id: "family"') && contents["app.js"].includes('{ id: "death"') && !contents["app.js"].includes("Projet maison") && !contents["app.js"].includes("Fête familiale")],
  ["aucune identité fictive", !contents["index.html"].includes("Mahamadou") && !contents["app.js"].includes("Aminata") && !contents["app.js"].includes("Ousmane")],
  ["aucune déclaration membre", !contents["index.html"].includes("Déclarer un paiement") && !contents["app.js"].includes("openPaymentDeclaration")],
  ["paiement réservé à la gestion", contents["index.html"].includes('data-action="record-cash"') && contents["index.html"].includes("Réservé aux personnes habilitées") && contents["app.js"].includes("canRecordCash()")],
  ["espèces uniquement", contents["index.html"].includes('value="Espèces" readonly') && contents["supabase-client.js"].includes('recordCashPayment') && contents["supabase/migrations/202607180001_initial_schema.sql"].includes("check (method = 'cash')")],
  ["micro informatif uniquement", contents["index.html"].includes("Consultation vocale uniquement") && !contents["index.html"].includes('data-voice-command="payment"') && !contents["app.js"].includes('executeVoiceCommand("payment")')],
  ["reconnaissance et synthèse vocales", contents["app.js"].includes("SpeechRecognition") && contents["app.js"].includes("SpeechSynthesisUtterance")],
  ["configuration Vercel", contents["vercel.json"].includes("X-Content-Type-Options")]
];

checks.push(["build statique Vercel", contents["vercel.json"].includes('"outputDirectory": "dist"') && contents["scripts/build.mjs"].includes("Build statique")]);
checks.push(["configuration Supabase publique séparée", contents["index.html"].includes("config.js?v=1") && !contents["config.js"].includes("supabase.co")]);
checks.push(["client Supabase authentifié", contents["index.html"].includes("supabase-client.js?v=15") && contents["supabase-client.js"].includes("Authorization: `Bearer") && contents["app.js"].includes("syncFromBackend")]);
checks.push(["connexion conservée si migration 010 absente", contents["supabase-client.js"].includes("loadMemberFundSchedules") && contents["supabase-client.js"].includes("paid_through_month|schema cache") && contents["app.js"].includes('title.textContent = "Connexion conservée"') && contents["app.js"].includes("if (syncError || !workspace?.user)")]);
checks.push(["connexion admin par mot de passe", contents["index.html"].includes('id="auth-password"') && contents["supabase-client.js"].includes('grant_type=password') && contents["app.js"].includes("signInWithPassword(email, password)")]);
checks.push(["création du mot de passe admin", contents["index.html"].includes('id="admin-password-form"') && contents["supabase-client.js"].includes("updatePassword") && contents["app.js"].includes("submitAdminPassword")]);
checks.push(["lien de connexion de secours", contents["index.html"].includes('data-action="send-login-link"') && contents["app.js"].includes("sendLoginLink") && contents["supabase-client.js"].includes("sendMagicLink")]);
checks.push(["RLS activée sur les paiements", contents["supabase/migrations/202607180001_initial_schema.sql"].includes("alter table public.cash_payments enable row level security") && contents["supabase/migrations/202607180001_initial_schema.sql"].includes("cash_payments_select_scope")]);
checks.push(["aucune écriture financière locale", !contents["app.js"].includes("state.payments.unshift") && contents["app.js"].includes("recordCashPayment")]);
checks.push(["mensualités de 5 euros depuis 2021", contents["supabase/migrations/202607180001_initial_schema.sql"].includes("monthly_amount numeric") && contents["supabase/migrations/202607180001_initial_schema.sql"].includes("date '2021-01-01'")]);
checks.push(["allocation sur les plus anciennes échéances", contents["supabase/migrations/202607180001_initial_schema.sql"].includes("record_cash_payment") && contents["supabase/migrations/202607180001_initial_schema.sql"].includes("cash_payment_allocations")]);
checks.push(["affichage séparé et dynamique des caisses", contents["index.html"].includes('id="contribution-fund-switch"') && contents["index.html"].includes('id="cash-fund-switch"') && contents["app.js"].includes("renderFundSelectors")]);
checks.push(["paiement rapide immédiatement visible aux habilités", contents["index.html"].includes('id="quick-payment-fab"') && contents["index.html"].includes("Ajouter un paiement") && contents["app.js"].includes('classList.toggle("hidden", !canRecordCash())')]);
checks.push(["configuration administrateur des caisses", contents["index.html"].includes("fund-config-form") && contents["supabase-client.js"].includes("configureFund")]);
checks.push(["paramétrage caisse accessible depuis les caisses", contents["index.html"].includes('id="fund-config-shortcut"') && contents["app.js"].includes('classList.toggle("hidden", !isAdministrator())') && contents["app.js"].includes("shortcut.dataset.editFund = fund.id")]);
checks.push(["nouveaux comptes en attente", contents["supabase/migrations/202607180002_member_approval_and_activity.sql"].includes("'pending', 'read'") && contents["app.js"].includes("Compte en attente de validation")]);
checks.push(["validation administrateur des droits", contents["supabase/migrations/202607180002_member_approval_and_activity.sql"].includes("review_member_access") && contents["index.html"].includes("Comptes et droits") && contents["supabase-client.js"].includes("reviewMemberAccess")]);
checks.push(["lecture seule ou saisie par caisse", contents["supabase/migrations/202607180002_member_approval_and_activity.sql"].includes("access_level in ('read', 'write')") && contents["index.html"].includes("lecture seule ou saisie sur une caisse précise")]);
checks.push(["activité générale sécurisée", contents["supabase/migrations/202607180002_member_approval_and_activity.sql"].includes("list_payment_activity") && contents["supabase/migrations/202607180002_member_approval_and_activity.sql"].includes("case when reveal_names") && contents["index.html"].includes("Mouvements généraux")]);
checks.push(["écriture limitée par caisse dynamique", contents["supabase/migrations/202607180003_member_fund_schedules.sql"].includes("can_record_fund") && contents["supabase/migrations/202607190007_dynamic_funds_and_due_refresh.sql"].includes("join public.funds fund") && contents["app.js"].includes("fundChoices")]);
checks.push(["admin avec écriture sur toutes les caisses", contents["supabase/migrations/202607180003_member_fund_schedules.sql"].includes("member.role = 'admin' or fund.code = any(member.write_fund_codes)") && contents["app.js"].includes("return availableCodes")]);
checks.push(["mensualités rétroactives par membre et caisse", contents["index.html"].includes('id="member-schedule-form"') && contents["supabase-client.js"].includes("setMemberFundSchedule") && contents["supabase/migrations/202607180003_member_fund_schedules.sql"].includes("member_fund_schedules")]);
checks.push(["paiements existants préservés", contents["supabase/migrations/202607180003_member_fund_schedules.sql"].includes("amount_paid = 0") && contents["index.html"].includes("Les mensualités déjà payées conservent leur montant historique")]);
checks.push(["deux parcours de connexion distincts", contents["index.html"].includes('data-auth-mode="member"') && contents["index.html"].includes('data-auth-mode="admin"') && contents["app.js"].includes("setAuthMode")]);
checks.push(["première connexion sans email", contents["index.html"].includes("Première connexion") && contents["index.html"].includes('id="membership-request-pseudo"') && contents["supabase-client.js"].includes("requestPseudoMembership")]);
checks.push(["connexion membre pseudo et code", contents["index.html"].includes('id="member-login-code"') && contents["index.html"].includes("Connexion avec code") && contents["supabase-client.js"].includes("signInMember")]);
checks.push(["code membre à six chiffres", contents["supabase/migrations/202607180004_pseudo_member_login.sql"].includes("lpad(floor(random() * 1000000)") && contents["index.html"].includes('pattern="[0-9]{6}"')]);
checks.push(["code stocké sous forme chiffrée", contents["supabase/migrations/202607180004_pseudo_member_login.sql"].includes("login_code_hash") && contents["supabase/migrations/202607180004_pseudo_member_login.sql"].includes("crypt(access_code, gen_salt('bf', 10))")]);
checks.push(["protection contre les essais de code", contents["supabase/migrations/202607180004_pseudo_member_login.sql"].includes("failed_login_attempts") && contents["supabase/migrations/202607180004_pseudo_member_login.sql"].includes("interval '15 minutes'")]);
checks.push(["session anonyme revendiquée après code", contents["supabase/migrations/202607180004_pseudo_member_login.sql"].includes("claim_member_login") && contents["supabase-client.js"].includes("signInAnonymously")]);
checks.push(["admin remet ou réinitialise le code", contents["index.html"].includes('id="member-code-modal"') && contents["app.js"].includes("resetMemberLoginCode") && contents["supabase-client.js"].includes("resetMemberLoginCode")]);
checks.push(["montant ventilé sur les arriérés", contents["index.html"].includes('id="payment-allocation-preview"') && contents["app.js"].includes("paymentAllocationFor") && contents["supabase/migrations/202607180005_payment_allocation_and_member_deletion.sql"].includes("order by period_start")]);
checks.push(["statuts paiement cohérents", contents["supabase/migrations/202607180005_payment_allocation_and_member_deletion.sql"].includes("'partial', 'paid'") && contents["supabase/migrations/202607180005_payment_allocation_and_member_deletion.sql"].includes("contribution_periods_status_check")]);
checks.push(["périodes admises depuis janvier 2021", contents["supabase/migrations/202607180005_payment_allocation_and_member_deletion.sql"].includes("normalized_start < date '2021-01-01'") && !contents["supabase/migrations/202607180005_payment_allocation_and_member_deletion.sql"].includes("normalized_start < greatest" )]);
checks.push(["suppression administrateur protégée", contents["index.html"].includes('id="delete-member-form"') && contents["supabase-client.js"].includes("deleteFamilyMember") && contents["supabase/migrations/202607180005_payment_allocation_and_member_deletion.sql"].includes("delete_family_member") && contents["supabase/migrations/202607180005_payment_allocation_and_member_deletion.sql"].includes("target.user_id = auth.uid()")]);
checks.push(["aucun choix manuel du nombre de mensualités", !contents["index.html"].includes("data-month-count") && !contents["app.js"].includes("paymentMonthCount") && contents["app.js"].includes("paymentAllocationFor")]);
checks.push(["mensualités dues réservées à l’administrateur", contents["index.html"].includes("Administrateur uniquement") && contents["app.js"].includes('section.classList.toggle("hidden", !isAdministrator())') && contents["supabase/migrations/202607180006_payment_reversals_and_push.sql"].includes("Seul un administrateur peut définir les mensualités dues")]);
checks.push(["gestion compacte et filtrable", contents["index.html"].includes("management-panel") && contents["index.html"].includes('id="member-access-search"') && contents["styles.css"].includes("max-height: 520px")]);
checks.push(["vue globale retirée de l’accueil", !contents["index.html"].includes('class="fund-snapshot"') && !contents["index.html"].includes('id="home-collected"')]);
checks.push(["annulation traçable des paiements", contents["index.html"].includes('id="reverse-payment-form"') && contents["app.js"].includes("reverseCashPayment") && contents["supabase/migrations/202607180006_payment_reversals_and_push.sql"].includes("reversal_reason = trim(reason)")]);
checks.push(["dépenses contrôlées par caisse", contents["index.html"].includes('id="expense-form"') && contents["supabase-client.js"].includes("recordCashExpense") && contents["supabase/migrations/202607180006_payment_reversals_and_push.sql"].includes("create table if not exists public.cash_expenses") && contents["supabase/migrations/202607180006_payment_reversals_and_push.sql"].includes("Solde insuffisant")]);
checks.push(["solde net et dépenses dans activité", contents["app.js"].includes("fundBalance") && contents["app.js"].includes('movement.method === "expense"') && contents["index.html"].includes("Solde net")]);
checks.push(["notifications push réelles", contents["sw.js"].includes('addEventListener("push"') && contents["app.js"].includes("pushManager.subscribe") && contents["supabase/functions/send-payment-push/index.ts"].includes("sendNotification") && contents["scripts/build.mjs"].includes("NEXT_PUBLIC_VAPID_PUBLIC_KEY")]);
checks.push(["ajout administrateur de caisse", contents["index.html"].includes('data-action="create-fund"') && contents["supabase-client.js"].includes("createFund") && contents["supabase/migrations/202607190007_dynamic_funds_and_due_refresh.sql"].includes("function public.create_fund")]);
checks.push(["mensualités prolongées automatiquement", contents["supabase-client.js"].includes("refresh_due_periods") && contents["supabase/migrations/202607190007_dynamic_funds_and_due_refresh.sql"].includes("greatest(\n          public.member_fund_schedules.end_month")]);
checks.push(["règlement explicite de tous les arriérés", contents["index.html"].includes("Régler tous les arriérés") && contents["app.js"].includes("settlePaymentArrears") && contents["app.js"].includes("Montant global des arriérés")]);
checks.push(["référence à jour et montant déduit depuis 2021", contents["index.html"].includes('id="schedule-settle-through"') && !contents["index.html"].includes("Calculer les mensualités dues") && contents["app.js"].includes("inferredPaid") && contents["app.js"].includes("setMemberPaidThrough") && !contents["app.js"].includes("recordCashPaymentThroughMonth") && contents["supabase-client.js"].includes("record_paid_through_movement") && contents["supabase/migrations/202607190010_paid_through_baseline.sql"].includes("paid_through_month") && contents["supabase/migrations/202607190011_paid_through_cash_movement.sql"].includes("amount_to_record")]);
checks.push(["mise à jour enregistrée dans les mouvements et la caisse", contents["index.html"].includes("ajouté au solde de la caisse et visible dans Activité") && contents["supabase-client.js"].includes("record_paid_through_movement") && contents["app.js"].includes("amount_recorded") && contents["app.js"].includes("ajoutés à") && contents["supabase/migrations/202607190011_paid_through_cash_movement.sql"].includes("public.record_cash_payment") && contents["supabase/migrations/202607190011_paid_through_cash_movement.sql"].includes("public.cash_payment_allocations")]);
checks.push(["import historique CSV et Excel", contents["index.html"].includes('id="payment-import-file"') && contents["app.js"].includes("rowsFromCSV") && contents["app.js"].includes("rowsFromXLSX") && contents["supabase/migrations/202607190008_governance_import_and_meeting.sql"].includes("import_cash_payments") && contents["scripts/build.mjs"].includes("fflate")]);
checks.push(["exceptions de cotisation protégées", contents["index.html"].includes('id="member-exception-form"') && contents["supabase/migrations/202607190008_governance_import_and_meeting.sql"].includes("set_member_fund_exception") && contents["app.js"].includes("submitMemberException")]);
checks.push(["droits multi-caisses arbitraires", contents["app.js"].includes("fund-access-check") && contents["app.js"].includes("saveSelectedFundAccess") && contents["supabase/migrations/202607190007_dynamic_funds_and_due_refresh.sql"].includes("cardinality(write_fund_codes) <= 50")]);
checks.push(["dépenses enrichies et double validation", contents["index.html"].includes('id="expense-receipt"') && contents["index.html"].includes('id="fund-config-threshold"') && contents["supabase/migrations/202607190008_governance_import_and_meeting.sql"].includes("review_cash_expense") && contents["supabase-client.js"].includes("uploadExpenseReceipt")]);
checks.push(["rappel push mensuel côté serveur", contents["supabase/functions/send-due-reminders/index.ts"].includes("Rappel mensuel de cotisations") && contents["supabase/functions/send-due-reminders/index.ts"].includes("sendNotification") && contents["supabase/cron/setup_due_reminders.sql.template"].includes("'0 8 1 * *'")]);
checks.push(["aucun rappel local quotidien", !contents["app.js"].includes("maybeNotifyDueSummary") && !contents["app.js"].includes("due-summary-")]);
checks.push(["journal administratif", contents["index.html"].includes('id="admin-audit-list"') && contents["supabase/migrations/202607190008_governance_import_and_meeting.sql"].includes("admin_audit_events") && contents["app.js"].includes("renderAdminAudit")]);
checks.push(["mode réunion sans identités", contents["index.html"].includes("Aucun nom, pseudo ou retard individuel") && contents["supabase/migrations/202607190008_governance_import_and_meeting.sql"].includes("get_meeting_summary") && contents["app.js"].includes("openMeetingMode")]);

for (const file of ["app.js", "supabase-client.js", "sw.js", "server.mjs", "scripts/build.mjs", "scripts/check.mjs"]) {
  const result = spawnSync(process.execPath, ["--check", join(root, file)], { encoding: "utf8" });
  checks.push([`syntaxe ${file}`, result.status === 0]);
  if (result.status !== 0) process.stderr.write(result.stderr);
}

let failed = false;
for (const [label, passed] of checks) {
  console.log(`${passed ? "✓" : "✗"} ${label}`);
  if (!passed) failed = true;
}

if (failed) process.exit(1);
console.log(`\n${checks.length} contrôles réussis.`);
